### ISSUE TITLE
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by UmerAfzal1** [wirecard/paymentSDK-iOS#43] opened 2020-11-27 17:30 UTC
After adding in pod and build in xcode 12 showing  error 
"Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.3 compiler: /Users/Desktop/Ios Apps/app/PaymentSDK.framework/Modules/PaymentSDK.swiftmodule/x86_64.swiftmodule"

**Comment by UmerAfzal1** [comment] 2020-12-01 12:40
Can you Please provide solution i'm waiting your kind response.
Thanks

**Comment by comanl** [comment] 2020-12-01 14:08
Hi,

we are working on this and soon will post an update. 

Cheers,
Liviu

**Comment by comanl** [comment] 2020-12-01 14:11
Duplicate of #39

**Closed** 2020-12-01 14:13 UTC

**Comment by comanl** [comment] 2020-12-10 16:30
Please check our new artifact compiled with Xcode 12.2 / Swift 5.3
